#!/usr/bin/env bash

. "${HOME}/.profile"

# start ssh-agent with gpg-agent
unset SSH_AGENT_PID
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

. "${HOME}/.cache/wal/colors.sh"

monitors=($(bspc query -M))
case "${#monitors[@]}" in
    1)
        bspc_monitors.sh 0
       ;;
    2)
        bspc_monitors.sh 0 1
       ;;
    3)
        bspc_monitors.sh 0 1 2
       ;;
    4)
       bspc monitor "${monitors[0]}" -d internet files books
       bspc monitor "${monitors[1]}" -d coding files2
       bspc monitor "${monitors[2]}" -d video files3 
       bspc monitor "${monitors[3]}" -d chat music windows
       ;;
esac

bspc config active_border_color ${background:-000000}
bspc config border_width 2
bspc config borderless_monocle false
bspc config bottom_padding 27
bspc config focus_follows_pointer false
bspc config focused_border_color ${foreground:-ffffff}
bspc config gapless_monocle false
bspc config ignore_ewmh_focus true
bspc config normal_border_color ${background:-000000}
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_follows_monitor false
bspc config pointer_modifier mod1
bspc config presel_feedback_color ${foreground:-ffffff}
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config window_gap 50

bspc rule -a *:floating_window state=floating
bspc rule -a floating_window:* state=floating
bspc rule -a Zathura state=tiled

bspc rule -a firefox desktop="internet"
bspc rule -a Spotify desktop="music"
bspc rule -a steam desktop="video"
bspc rule -a discord desktop="files3"

bspc desktop internet -l monocle
bspc desktop music -l monocle
bspc desktop video -l monocle
bspc desktop files -l monocle
bspc desktop files2 -l monocle
bspc desktop files3 -l monocle

xrdb ~/.Xresources
pgrep sxhkd >/dev/null || sxhkd &
pgrep xbanish >/dev/null || xbanish &
pgrep light-locker >/dev/null || light-locker &
pgrep lxpolkit >/dev/null | lxpolkit &
~/.config/polybar/launch.sh &

systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --user start picom

if [[ "${HOSTNAME}" == "wigeon" ]]; then
    systemctl --user start sunshine
    systemctl --user start ha-mqtt-iot
fi

if [[ "${HOSTNAME}" == "teal" ]]; then
    # set touchpad middle click to left click
    xinput set-button-map "CUST0001:00 06CB:76AF Touchpad" 1 1 3 4 5 6 7
fi

if [ -f ~/.local/share/background/1 ]; then
    feh --bg-fill ~/.local/share/background/*
else
    feh --bg-fill -z /usr/share/backgrounds/pokemon
fi

# ~/.scripts/playerctl.sh daemon &

xsetroot -cursor_name left_ptr
setxkbmap -option caps:backspace

playerctld daemon
