#!/usr/bin/env bash

for i in COMPATIBLE_BRANDS MAJOR_BRAND MINOR_VERSION RELEASETIME SORT_ALBUM SORT_ALBUM_ARTIST SORT_ARTIST SORT_COMPOSER SORT_NAME PUBLISHER COMPOSERLYRICIST ; do
    metaflac --remove-tag="${i}" -- *.flac
done
