#!/usr/bin/env bash

for i in \
    COMPATIBLE_BRANDS \
    MAJOR_BRAND \
    MINOR_VERSION \
    RELEASETIME \
    SORT_ALBUM \
    SORT_ALBUM_ARTIST \
    SORT_ARTIST \
    SORT_COMPOSER \
    SORT_NAME \
    PUBLISHER \
    COMPOSERLYRICIST \
    CREATION_TIME \
    MAIN_ARTIST \
    LENGTH \
    BPM \
    EXPLICIT \
    ORGANIZATION \
    MUSICBRAINZ_TRACKID \
    MUSICBRAINZ_ALBUMID \
    MUSICBRAINZ_ARTISTID \
    MUSICBRAINZ_ALBUMARTISTID \
    MUSICBRAINZ_DISCID \
    MCN \
    iTunes_CDDB_1 \
    ENCODER \
    TRACKTOTAL \
    COMPILATION \
    GAPLESS_PLAYBACK \
    RATING \
    MEDIA_TYPE \
    TIDAL_DATA \
    TIDAL_ALBUM_ID \
    TIDAL_ALBUM_URL \
    TIDAL_TRACK_ID \
    TIDAL_TRACK_URL \
    ALBUM_RELEASE_DATE \
    ITUNESADVISORY; do
    metaflac --remove-tag="${i}" -- *.flac
done
